### ISSUE TITLE
How to reproduce the new rolled out features in my project?

### ISSUE THREAD

**Issue by harishankards** [epicmaxco/vuestic-admin#192] opened 2018-05-04 03:37 UTC
Hi,
I have developed a lot of things over the vuestic-admin. Now, I want the latest features, without disturbing my components and functionalities. How would I do that? Won't git pull spoil mine?

**Comment by smartapant** [comment] 2018-05-10 09:50
@harishankards which version are you using?

**Comment by harishankards** [comment] 2018-05-10 12:32
@smartapant, I typed `vuestic --version` in my terminal and got `0.1.1`.

Is this how I need to check the version? I installed 2 months back only.

**Comment by harishankards** [comment] 2018-05-14 05:35
Hi @smartapant, just wanted to check whether have you had a chance to look into this.

**Comment by smartapant** [comment] 2018-05-14 17:41
@harishankards please check package.json file :)

**Comment by harishankards** [comment] 2018-05-14 22:53
Oh, thanks! Mine is 1.4.0 @smartapant.

**Comment by smartapant** [comment] 2018-05-16 11:57
Duplicate of #204

**Closed by smartapant** 2018-05-16 11:57 UTC
