### ISSUE TITLE
Button group has incorrect gradient

### ISSUE THREAD

**Issue by smartapant** [epicmaxco/vuestic-admin#520] opened 2019-03-29 16:37 UTC
I'm submitting a bug report.
  
* **What is the current behavior?**
Button group's btns have visible 'gradient borders'
![Screen Shot 2019-03-29 at 7 34 54 PM](https://user-images.githubusercontent.com/3674348/55247945-df187600-5259-11e9-861d-e1a7f05d0b44.png)

* **What is the expected behavior?**
![Screen Shot 2019-03-29 at 7 34 24 PM](https://user-images.githubusercontent.com/3674348/55247970-ef305580-5259-11e9-8274-e5baab96364e.png)

**Comment by asvae** [comment] 2019-04-06 00:13
Fixed in `develop`

**Comment by smartapant** [comment] 2019-06-18 14:08
@asvae still present in develop

**Comment by smellyshovel** [comment] 2019-07-13 16:11
The problem is due to the fact that all the buttons have gradients by themselves. Therefore each individual button's gradient overlaps their common gradient.

For all the buttons in a group to share the same gradient it seems necessary to have an "underlayer" with that gradient and to make the buttons transparent.

![Screenshot_20190713_185251](https://user-images.githubusercontent.com/9782236/61173700-89b16c00-a59f-11e9-85f7-044f739cce34.png)

Here comes a drawback however: flat and outlined buttons start sharing their common gradient as well (since there's no way to determine which kind of buttons are included in a group to disable such a behavior for flat and outlined ones)

![Screenshot_20190713_185825](https://user-images.githubusercontent.com/9782236/61173752-4e636d00-a5a0-11e9-8835-5a2350b4b686.png)

I could try to force these to be white, but that don't seem get along nicely with our future plans to implement a dark theme.

-----

The other possible option is to allow users to provide additional props to buttons groups (as we do with [Button Toggles](https://github.com/epicmaxco/vuestic-admin/wiki/Buttons#button-toggles)). I believe that this is the most beautiful solution out there requiring, however, **an API change**.

Would like to here your opinion on that.

P.S. That solution also makes a user to use all the same buttons inside a group (now it's possible to use a group with both the outlined and flat (e.g.) buttons at the same time, which I don't think is a good idea).

P.P.S. Will possibly need to do something with the way we treat hovered and focused buttons then. But not sure

**Comment by smellyshovel** [comment] 2019-07-13 16:18
Also. You can see on the first screenshot above that each button has its own box-shadow which overlap each other. Doesn't seem good to me.

If we decide to share a common gradient between all the buttons then it would become impossible to manage shadows for different buttons' states.

If we rather decide to keep these as they are and want them to look nicely then there's no point to consider my last suggestion (on the API change), because we'd have to come up with some mechanism to split gradients for each button separately.

**@asvae, Need guidance**

**Comment by smellyshovel** [comment] 2019-07-15 14:07
Seems like there's no way to make gradients work without breaking anything else, so it was decided to implements solid buttons instead. Gradients still work for non-grouped buttons though. Will close this one after #594 is merged.

**Closed** 2019-07-15 15:30 UTC
Labels: bug
